// 20240323092405
// https://opentdb.com/api.php?amount=50&category=18&type=multiple

const newQuestions = {
  response_code: 0,
  results: [
    {
      type: "multiple",
      difficulty: "hard",
      category: "Science: Computers",
      question: "The Harvard architecture for micro-controllers added which additional bus?",
      correct_answer: "Instruction",
      incorrect_answers: ["Address", "Data", "Control"],
    },
    {
      type: "multiple",
      difficulty: "easy",
      category: "Science: Computers",
      question: "The programming language &#039;Swift&#039; was created to replace what other programming language?",
      correct_answer: "Objective-C",
      incorrect_answers: ["C#", "Ruby", "C++"],
    },
    {
      type: "multiple",
      difficulty: "medium",
      category: "Science: Computers",
      question: "On which day did the World Wide Web go online?",
      correct_answer: "December 20, 1990",
      incorrect_answers: ["December 17, 1996", "November 12, 1990", "November 24, 1995"],
    },
    {
      type: "multiple",
      difficulty: "easy",
      category: "Science: Computers",
      question: "In web design, what does CSS stand for?",
      correct_answer: "Cascading Style Sheet",
      incorrect_answers: ["Counter Strike: Source", "Corrective Style Sheet", "Computer Style Sheet"],
    },
    {
      type: "multiple",
      difficulty: "medium",
      category: "Science: Computers",
      question: "Which coding language was the #1 programming language in terms of usage on GitHub in 2015?",
      correct_answer: "JavaScript",
      incorrect_answers: ["C#", "Python", "PHP"],
    },
    {
      type: "multiple",
      difficulty: "hard",
      category: "Science: Computers",
      question: "What was the first company to use the term &quot;Golden Master&quot;?",
      correct_answer: "Apple",
      incorrect_answers: ["IBM", "Microsoft", "Google"],
    },
    {
      type: "multiple",
      difficulty: "medium",
      category: "Science: Computers",
      question: "Moore&#039;s law originally stated that the number of transistors on a microprocessor chip would double every...",
      correct_answer: "Year",
      incorrect_answers: ["Four Years", "Two Years", "Eight Years"],
    },
    {
      type: "multiple",
      difficulty: "easy",
      category: "Science: Computers",
      question: "If you were to code software in this language you&#039;d only be able to type 0&#039;s and 1&#039;s.",
      correct_answer: "Binary",
      incorrect_answers: ["JavaScript", "C++", "Python"],
    },
    {
      type: "multiple",
      difficulty: "easy",
      category: "Science: Computers",
      question: "This mobile OS held the largest market share in 2012.",
      correct_answer: "iOS",
      incorrect_answers: ["Android", "BlackBerry", "Symbian"],
    },
    {
      type: "multiple",
      difficulty: "medium",
      category: "Science: Computers",
      question: "What is the correct term for the metal object in between the CPU and the CPU fan within a computer system?",
      correct_answer: "Heat Sink",
      incorrect_answers: ["CPU Vent", "Temperature Decipator", "Heat Vent"],
    },
    {
      type: "multiple",
      difficulty: "easy",
      category: "Science: Computers",
      question: "The series of the Intel HD graphics generation succeeding that of the 5000 and 6000 series (Broadwell) is called:",
      correct_answer: "HD Graphics 500",
      incorrect_answers: ["HD Graphics 700 ", "HD Graphics 600", "HD Graphics 7000"],
    },
    {
      type: "multiple",
      difficulty: "hard",
      category: "Science: Computers",
      question: "Which of the following is the oldest of these computers by release date?",
      correct_answer: "TRS-80",
      incorrect_answers: ["Commodore 64", "ZX Spectrum", "Apple 3"],
    },
    {
      type: "multiple",
      difficulty: "medium",
      category: "Science: Computers",
      question: "Which of these people was NOT a founder of Apple Inc?",
      correct_answer: "Jonathan Ive",
      incorrect_answers: ["Steve Jobs", "Ronald Wayne", "Steve Wozniak"],
    },
    {
      type: "multiple",
      difficulty: "easy",
      category: "Science: Computers",
      question: "The C programming language was created by this American computer scientist. ",
      correct_answer: "Dennis Ritchie",
      incorrect_answers: ["Tim Berners Lee", "al-Khwārizmī", "Willis Ware"],
    },
    {
      type: "multiple",
      difficulty: "medium",
      category: "Science: Computers",
      question: "Which of these programming languages is a low-level language?",
      correct_answer: "Assembly",
      incorrect_answers: ["Python", "C#", "Pascal"],
    },
    {
      type: "multiple",
      difficulty: "hard",
      category: "Science: Computers",
      question: "Which of these names was an actual codename for a cancelled Microsoft project?",
      correct_answer: "Neptune",
      incorrect_answers: ["Enceladus", "Pollux", "Saturn"],
    },
    {
      type: "multiple",
      difficulty: "easy",
      category: "Science: Computers",
      question: "What is the domain name for the country Tuvalu?",
      correct_answer: ".tv",
      incorrect_answers: [".tu", ".tt", ".tl"],
    },
    {
      type: "multiple",
      difficulty: "medium",
      category: "Science: Computers",
      question: "What does RAID stand for?",
      correct_answer: "Redundant Array of Independent Disks",
      incorrect_answers: ["Rapid Access for Indexed Devices", "Range of Applications with Identical Designs", "Randomized Abstract Identification Description"],
    },
    {
      type: "multiple",
      difficulty: "medium",
      category: "Science: Computers",
      question: "Unix Time is defined as the number of seconds that have elapsed since when?",
      correct_answer: "Midnight, January 1, 1970",
      incorrect_answers: ["Midnight, July 4, 1976", "Midnight on the creator of Unix&#039;s birthday", "Midnight, July 4, 1980"],
    },
    {
      type: "multiple",
      difficulty: "medium",
      category: "Science: Computers",
      question: "Generally, which component of a computer draws the most power?",
      correct_answer: "Video Card",
      incorrect_answers: ["Hard Drive", "Processor", "Power Supply"],
    },
    {
      type: "multiple",
      difficulty: "medium",
      category: "Science: Computers",
      question: ".rs is the top-level domain for what country?",
      correct_answer: "Serbia",
      incorrect_answers: ["Romania", "Russia", "Rwanda"],
    },
    {
      type: "multiple",
      difficulty: "medium",
      category: "Science: Computers",
      question: "In programming, the ternary operator is mostly defined with what symbol(s)?",
      correct_answer: "?:",
      incorrect_answers: ["??", "if then", "?"],
    },
    {
      type: "multiple",
      difficulty: "medium",
      category: "Science: Computers",
      question: "Which of the following languages is used as a scripting language in the Unity 3D game engine?",
      correct_answer: "C#",
      incorrect_answers: ["Java", "C++", "Objective-C"],
    },
    {
      type: "multiple",
      difficulty: "hard",
      category: "Science: Computers",
      question: "Which of these was the name of a bug found in April 2014 in the publicly available OpenSSL cryptography library?",
      correct_answer: "Heartbleed",
      incorrect_answers: ["Shellshock", "Corrupted Blood", "Shellscript"],
    },
    {
      type: "multiple",
      difficulty: "medium",
      category: "Science: Computers",
      question: "Whistler was the codename of this Microsoft Operating System.",
      correct_answer: "Windows XP",
      incorrect_answers: ["Windows 2000", "Windows 7", "Windows 95"],
    },
    {
      type: "multiple",
      difficulty: "hard",
      category: "Science: Computers",
      question: "What is the codename of the eighth generation Intel Core micro-architecture launched in October 2017?",
      correct_answer: "Coffee Lake",
      incorrect_answers: ["Sandy Bridge", "Skylake", "Broadwell"],
    },
    {
      type: "multiple",
      difficulty: "medium",
      category: "Science: Computers",
      question: "What is the number of keys on a standard Windows Keyboard?",
      correct_answer: "104",
      incorrect_answers: ["64", "94", "76"],
    },
    {
      type: "multiple",
      difficulty: "medium",
      category: "Science: Computers",
      question: "What does the &#039;S&#039; in the RSA encryption algorithm stand for?",
      correct_answer: "Shamir",
      incorrect_answers: ["Secure", "Schottky", "Stable"],
    },
    {
      type: "multiple",
      difficulty: "hard",
      category: "Science: Computers",
      question: "Which of these Cherry MX mechanical keyboard switches is both tactile and clicky?",
      correct_answer: "Cherry MX Blue",
      incorrect_answers: ["Cherry MX Black", "Cherry MX Red", "Cherry MX Brown"],
    },
    {
      type: "multiple",
      difficulty: "easy",
      category: "Science: Computers",
      question: "What is the code name for the mobile operating system Android 7.0?",
      correct_answer: "Nougat",
      incorrect_answers: ["Ice Cream Sandwich", "Jelly Bean", "Marshmallow"],
    },
    {
      type: "multiple",
      difficulty: "hard",
      category: "Science: Computers",
      question: "What was the name of the first Bulgarian personal computer?",
      correct_answer: "IMKO-1",
      incorrect_answers: ["Pravetz 82", "Pravetz 8D", "IZOT 1030"],
    },
    {
      type: "multiple",
      difficulty: "medium",
      category: "Science: Computers",
      question: "Laserjet and inkjet printers are both examples of what type of printer?",
      correct_answer: "Non-impact printer",
      incorrect_answers: ["Impact printer", "Daisywheel printer", "Dot matrix printer"],
    },
    {
      type: "multiple",
      difficulty: "hard",
      category: "Science: Computers",
      question: "What port does HTTP run on?",
      correct_answer: "80",
      incorrect_answers: ["53", "443", "23"],
    },
    {
      type: "multiple",
      difficulty: "easy",
      category: "Science: Computers",
      question: "Which computer hardware device provides an interface for all other connected devices to communicate?",
      correct_answer: "Motherboard",
      incorrect_answers: ["Central Processing Unit", "Hard Disk Drive", "Random Access Memory"],
    },
    {
      type: "multiple",
      difficulty: "easy",
      category: "Science: Computers",
      question: "In any programming language, what is the most common way to iterate through an array?",
      correct_answer: "&#039;For&#039; loops",
      incorrect_answers: ["&#039;If&#039; Statements", "&#039;Do-while&#039; loops", "&#039;While&#039; loops"],
    },
    {
      type: "multiple",
      difficulty: "easy",
      category: "Science: Computers",
      question: "The numbering system with a radix of 16 is more commonly referred to as ",
      correct_answer: "Hexidecimal",
      incorrect_answers: ["Binary", "Duodecimal", "Octal"],
    },
    {
      type: "multiple",
      difficulty: "hard",
      category: "Science: Computers",
      question: "What is the name given to layer 4 of the Open Systems Interconnection (ISO) model?",
      correct_answer: "Transport",
      incorrect_answers: ["Session", "Data link", "Network"],
    },
    {
      type: "multiple",
      difficulty: "hard",
      category: "Science: Computers",
      question: "Which of the following computer components can be built using only NAND gates?",
      correct_answer: "ALU",
      incorrect_answers: ["CPU", "RAM", "Register"],
    },
    {
      type: "multiple",
      difficulty: "medium",
      category: "Science: Computers",
      question: "What does AD stand for in relation to Windows Operating Systems? ",
      correct_answer: "Active Directory",
      incorrect_answers: ["Alternative Drive", "Automated Database", "Active Department"],
    },
    {
      type: "multiple",
      difficulty: "easy",
      category: "Science: Computers",
      question: "When Gmail first launched, how much storage did it provide for your email?",
      correct_answer: "1GB",
      incorrect_answers: ["512MB", "5GB", "Unlimited"],
    },
    {
      type: "multiple",
      difficulty: "easy",
      category: "Science: Computers",
      question: "How long is an IPv6 address?",
      correct_answer: "128 bits",
      incorrect_answers: ["32 bits", "64 bits", "128 bytes"],
    },
    {
      type: "multiple",
      difficulty: "medium",
      category: "Science: Computers",
      question: "How fast is USB 3.1 Gen 2 theoretically?",
      correct_answer: "10 Gb/s",
      incorrect_answers: ["5 Gb/s", "8 Gb/s", "1 Gb/s"],
    },
    {
      type: "multiple",
      difficulty: "medium",
      category: "Science: Computers",
      question: "Approximately how many Apple I personal computers were created?",
      correct_answer: "200",
      incorrect_answers: ["100", "500", "1000"],
    },
    {
      type: "multiple",
      difficulty: "easy",
      category: "Science: Computers",
      question: "In computing, what does LAN stand for?",
      correct_answer: "Local Area Network",
      incorrect_answers: ["Long Antenna Node", "Light Access Node", "Land Address Navigation"],
    },
    {
      type: "multiple",
      difficulty: "medium",
      category: "Science: Computers",
      question: "What is the name of the default theme that is installed with Windows XP?",
      correct_answer: "Luna",
      incorrect_answers: ["Neptune", "Whistler", "Bliss"],
    },
    {
      type: "multiple",
      difficulty: "hard",
      category: "Science: Computers",
      question: "Which of these is not a key value of Agile software development?",
      correct_answer: "Comprehensive documentation",
      incorrect_answers: ["Individuals and interactions", "Customer collaboration", "Responding to change"],
    },
    {
      type: "multiple",
      difficulty: "medium",
      category: "Science: Computers",
      question: "What does &quot;LCD&quot; stand for?",
      correct_answer: "Liquid Crystal Display",
      incorrect_answers: ["Language Control Design", "Last Common Difference", "Long Continuous Design"],
    },
    {
      type: "multiple",
      difficulty: "easy",
      category: "Science: Computers",
      question: "How many kilobytes in one gigabyte (in decimal)?",
      correct_answer: "1000000",
      incorrect_answers: ["1024", "1000", "1048576"],
    },
    {
      type: "multiple",
      difficulty: "easy",
      category: "Science: Computers",
      question: "According to the International System of Units, how many bytes are in a kilobyte of RAM?",
      correct_answer: "1000",
      incorrect_answers: ["512", "1024", "500"],
    },
    {
      type: "multiple",
      difficulty: "medium",
      category: "Science: Computers",
      question: "In HTML, which non-standard tag used to be be used to make elements scroll across the viewport?",
      correct_answer: "&lt;marquee&gt;&lt;/marquee&gt;",
      incorrect_answers: ["&lt;scroll&gt;&lt;/scroll&gt;", "&lt;move&gt;&lt;/move&gt;", "&lt;slide&gt;&lt;/slide&gt;"],
    },
    {
      type: "multiple",
      difficulty: "hard",
      category: "Science: Computers",
      question: "Which RAID array type is associated with data mirroring?",
      correct_answer: "RAID 1",
      incorrect_answers: ["RAID 0", "RAID 10", "RAID 5"],
    },
    {
      type: "multiple",
      difficulty: "medium",
      category: "Science: Computers",
      question: "When did the online streaming service &quot;Mixer&quot; launch?",
      correct_answer: "2016",
      incorrect_answers: ["2013", "2009", "2011"],
    },
    {
      type: "multiple",
      difficulty: "easy",
      category: "Science: Computers",
      question: "What is the most preferred image format used for logos in the Wikimedia database?",
      correct_answer: ".svg",
      incorrect_answers: [".png", ".jpeg", ".gif"],
    },
    {
      type: "multiple",
      difficulty: "medium",
      category: "Science: Computers",
      question: "In computing terms, typically what does CLI stand for?",
      correct_answer: "Command Line Interface",
      incorrect_answers: ["Common Language Input", "Control Line Interface", "Common Language Interface"],
    },
    {
      type: "multiple",
      difficulty: "hard",
      category: "Science: Computers",
      question: "The acronym &quot;RIP&quot; stands for which of these?",
      correct_answer: "Routing Information Protocol",
      incorrect_answers: ["Runtime Instance Processes", "Regular Interval Processes", "Routine Inspection Protocol"],
    },
    {
      type: "multiple",
      difficulty: "easy",
      category: "Science: Computers",
      question: "On Twitter, what was the original character limit for a Tweet?",
      correct_answer: "140",
      incorrect_answers: ["120", "160", "100"],
    },
    {
      type: "multiple",
      difficulty: "medium",
      category: "Science: Computers",
      question: "The name of technology company HP stands for what?",
      correct_answer: "Hewlett-Packard",
      incorrect_answers: ["Howard Packmann", "Husker-Pollosk", "Hellman-Pohl"],
    },
    {
      type: "multiple",
      difficulty: "easy",
      category: "Science: Computers",
      question: "What does LTS stand for in the software market?",
      correct_answer: "Long Term Support",
      incorrect_answers: ["Long Taco Service", "Ludicrous Transfer Speed", "Ludicrous Turbo Speed"],
    },
    {
      type: "multiple",
      difficulty: "medium",
      category: "Science: Computers",
      question: "What was the first Android version specifically optimized for tablets?",
      correct_answer: "Honeycomb",
      incorrect_answers: ["Eclair", "Froyo", "Marshmellow"],
    },
    {
      type: "multiple",
      difficulty: "hard",
      category: "Science: Computers",
      question: "What internet protocol was documented in RFC 1459?",
      correct_answer: "IRC",
      incorrect_answers: ["HTTP", "HTTPS", "FTP"],
    },
    {
      type: "multiple",
      difficulty: "medium",
      category: "Science: Computers",
      question: "What was the first commerically available computer processor?",
      correct_answer: "Intel 4004",
      incorrect_answers: ["Intel 486SX", "TMS 1000", "AMD AM386"],
    },
    {
      type: "multiple",
      difficulty: "hard",
      category: "Science: Computers",
      question: "The internet domain .fm is the country-code top-level domain for which Pacific Ocean island nation?",
      correct_answer: "Micronesia",
      incorrect_answers: ["Fiji", "Tuvalu", "Marshall Islands"],
    },
    {
      type: "multiple",
      difficulty: "easy",
      category: "Science: Computers",
      question: "What language does Node.js use?",
      correct_answer: "JavaScript",
      incorrect_answers: ["Java", "Java Source", "Joomla Source Code"],
    },
    {
      type: "multiple",
      difficulty: "medium",
      category: "Science: Computers",
      question: "What is known as &quot;the brain&quot; of the Computer?",
      correct_answer: "Central Processing Unit",
      incorrect_answers: ["Motherboard", "Graphics Processing Unit", "Keyboard"],
    },
    {
      type: "multiple",
      difficulty: "hard",
      category: "Science: Computers",
      question: "What major programming language does Unreal Engine 4 use?",
      correct_answer: "C++",
      incorrect_answers: ["Assembly", "C#", "ECMAScript"],
    },
    {
      type: "multiple",
      difficulty: "medium",
      category: "Science: Computers",
      question: "Nvidia&#039;s headquarters are based in which Silicon Valley city?",
      correct_answer: "Santa Clara",
      incorrect_answers: ["Palo Alto", "Cupertino", "Mountain View"],
    },
    {
      type: "multiple",
      difficulty: "hard",
      category: "Science: Computers",
      question: "Released in 2001, the first edition of Apple&#039;s Mac OS X operating system (version 10.0) was given what animal code name?",
      correct_answer: "Cheetah",
      incorrect_answers: ["Puma", "Tiger", "Leopard"],
    },
    {
      type: "multiple",
      difficulty: "hard",
      category: "Science: Computers",
      question: "What was the name of the security vulnerability found in Bash in 2014?",
      correct_answer: "Shellshock",
      incorrect_answers: ["Heartbleed", "Bashbug", "Stagefright"],
    },
    {
      type: "multiple",
      difficulty: "hard",
      category: "Science: Computers",
      question: "Dutch computer scientist Mark Overmars is known for creating which game development engine?",
      correct_answer: "Game Maker",
      incorrect_answers: ["Stencyl", "Construct", "Torque 2D"],
    },
    {
      type: "multiple",
      difficulty: "easy",
      category: "Science: Computers",
      question: "What does the Prt Sc button do?",
      correct_answer: "Captures what&#039;s on the screen and copies it to your clipboard",
      incorrect_answers: ["Nothing", "Saves a .png file of what&#039;s on the screen in your screenshots folder in photos", "Closes all windows"],
    },
    {
      type: "multiple",
      difficulty: "easy",
      category: "Science: Computers",
      question: "Which company was established on April 1st, 1976 by Steve Jobs, Steve Wozniak and Ronald Wayne?",
      correct_answer: "Apple",
      incorrect_answers: ["Microsoft", "Atari", "Commodore"],
    },
    {
      type: "multiple",
      difficulty: "medium",
      category: "Science: Computers",
      question: "How many bits make up the significand portion of a single precision floating point number?",
      correct_answer: "23",
      incorrect_answers: ["8", "53", "15"],
    },
    {
      type: "multiple",
      difficulty: "hard",
      category: "Science: Computers",
      question: "Who is the original author of the realtime physics engine called PhysX?",
      correct_answer: "NovodeX",
      incorrect_answers: ["Ageia", "Nvidia", "AMD"],
    },
    {
      type: "multiple",
      difficulty: "easy",
      category: "Science: Computers",
      question: "Which programming language shares its name with an island in Indonesia?",
      correct_answer: "Java",
      incorrect_answers: ["Python", "C", "Jakarta"],
    },
    {
      type: "multiple",
      difficulty: "hard",
      category: "Science: Computers",
      question: "Who is the founder of Palantir?",
      correct_answer: "Peter Thiel",
      incorrect_answers: ["Mark Zuckerberg", "Marc Benioff", "Jack Dorsey"],
    },
    {
      type: "multiple",
      difficulty: "hard",
      category: "Science: Computers",
      question: "According to DeMorgan&#039;s Theorem, the Boolean expression (AB)&#039; is equivalent to:",
      correct_answer: "A&#039; + B&#039;",
      incorrect_answers: ["A&#039;B + B&#039;A", "A&#039;B&#039;", "AB&#039; + AB"],
    },
    {
      type: "multiple",
      difficulty: "medium",
      category: "Science: Computers",
      question: "In CSS, which of these values CANNOT be used with the &quot;position&quot; property?",
      correct_answer: "center",
      incorrect_answers: ["static", "absolute", "relative"],
    },
    {
      type: "multiple",
      difficulty: "medium",
      category: "Science: Computers",
      question: "In programming, what do you call functions with the same name but different implementations?",
      correct_answer: "Overloading",
      incorrect_answers: ["Overriding", "Abstracting", "Inheriting"],
    },
    {
      type: "multiple",
      difficulty: "medium",
      category: "Science: Computers",
      question: "Which programming language was developed by Sun Microsystems in 1995?",
      correct_answer: "Java",
      incorrect_answers: ["Python", "Solaris OS", "C++"],
    },
    {
      type: "multiple",
      difficulty: "easy",
      category: "Science: Computers",
      question: "In the programming language Java, which of these keywords would you put on a variable to make sure it doesn&#039;t get modified?",
      correct_answer: "Final",
      incorrect_answers: ["Static", "Private", "Public"],
    },
    {
      type: "multiple",
      difficulty: "medium",
      category: "Science: Computers",
      question: "On which computer hardware device is the BIOS chip located?",
      correct_answer: "Motherboard",
      incorrect_answers: ["Hard Disk Drive", "Central Processing Unit", "Graphics Processing Unit"],
    },
  ],
};
